#title: AVERtek # your name photo (or website title) here
logo1: "/images/AVERtek-Logo-final-blue.png?raw=true" # your photo (or logo) here
logo2: "/images/XR-NOW.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>COMPUTER - View 3D Image:</b> <br>
    Use Pointer to rotate, spin; Use zoom to scale
  <br><br>
  <b>MOBILE - View in Augmented Reality (AR):</b> <br>
    Press AR button, place image in real space, anchor on surface, scale and view 
  <br><br>
  <a href="https://AVERtek.net/xr-asap-1/">Learn About XR-NOW</a> 
  <br><br>
  <a href="https://AVERtek.net/contact-us/">Contact AVERtek for More Information</a>  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
